fix: первая итерация 9го спринта
GSBoldyrev/java-filmorate pull request #1
Opened 2022-08-02 23:59 UTC by GSBoldyrev

1я итерация 9-го спринта

2022-08-03 18:15 UTC, FanaticFiz requested changes
Финальный комментарий, на Я.Практикуме.

2022-08-03 18:15 UTC, FanaticFiz commented on pom.xml
> +	</parent>
Вечер добрый!

`pom` файл желательно бы немного причесать: очень не хватает отделения друг от друга (пустыми строками) глобальных частей таких как parent, properties, dependencies

Хорошим тоном будет указать кодировку в properties
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

Советую прочитать про семантическое версионирование, ну а после не стесняйся, смело проставь версию!

2022-08-03 18:15 UTC, FanaticFiz commented on src/main/resources/application.properties
> +
Я буду топить за то чтобы ты сразу привыкать к написанию файла свойств для приложения в формате yaml -> application.yml

Соответственно - попрошу тебя этому следовать.
Как мини задание: задай порт для сервиса отличный от дефолтного, заодно можешь глянуть как задать чтобы порт был случайным.

2022-08-03 18:15 UTC, FanaticFiz commented on src/test/java/ru/yandex/practicum/filmorate/ValidatorTest.java
> +        // Arrange
Если тест маленький и каждый этап представлен одной - тремя строчками то можно не писать `// Arrange` `// Act`...
Достаточно отделять эти этапы пустой строкой.

2022-08-03 18:15 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +public class ValidationException extends Exception {
Найди и держи первое время рядом иерархию эксепшенов.
`Exception` это checked ексепшн. 
А нужен `RuntimeException`

2022-08-03 18:15 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/misc/Validator.java
> +            throw new ValidationException("Логин не может содержать пробелы!");
Да ты проверяешь валидны ли данные по своей логике, но ексепшн надо кинуть `BadRequestException` 
поскольку у нас веб сервис, а клиент прислал неверный запрос.

2022-08-03 18:15 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/misc/Validator.java
> +            user.setName(user.getLogin());
Валидатор должен только валидировать. С чего вдруг он начал менять пользователя?
Да и что это у тебя тут за логика с именем?

2022-08-03 18:15 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +            throw new ValidationException("Пользователь не найден!");
Не найден пользователь или какая другая сущность, ексепшн будет, какой...... ? 
`Not*****Exception` ))

2022-08-03 18:15 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +
Ну вот только начали проект, а уже бардак в коде ))

2022-08-03 22:19 UTC, GSBoldyrev commented on pom.xml
> +	</parent>
Привет!
Между всеми предыдущими заданиями и этими оказался довольно большой гэп. Сейчас чувствую, будто заново учиться начал. Ничего не понятно, но очень интересно))
Я надеюсь правильно понял, что могу оставлять комментарии тут.. Гитхаб даже подсказывает ,что я как то сразу сюда исправленный код могу добавлять, но боюсь.

2022-08-03 22:21 UTC, GSBoldyrev commented on src/main/resources/application.properties
> +
Понял, почитаю и сделаю. А что это за строка синего цвета перед кодом (@@ -0,0 +1 @@) ?

2022-08-03 22:21 UTC, GSBoldyrev commented on src/test/java/ru/yandex/practicum/filmorate/ValidatorTest.java
> +        // Arrange
Вот я и сомневался, что глуповато выглядит на маленьком тесте))

2022-08-03 22:22 UTC, GSBoldyrev commented on src/main/java/ru/yandex/practicum/filmorate/misc/Validator.java
> +            throw new ValidationException("Логин не может содержать пробелы!");
погоди.. А где тогда кидать наш эксепшн? Или я неправильно понял.. В каком случае будет BadRequest, а в каком Validation?

2022-08-03 22:23 UTC, GSBoldyrev commented on src/main/java/ru/yandex/practicum/filmorate/misc/Validator.java
> +            user.setName(user.getLogin());
Сейчас вижу да, что логики этой в валидаторе быть не должно. А должна ли она быть в целом? Просто в ТЗ написано, что если имя не задано в запросе, то вместо имени должен использоваться логин. Я понял это так, что имени нужно логин присвоить

2022-08-03 22:25 UTC, GSBoldyrev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +            throw new ValidationException("Пользователь не найден!");
Опять же... А зачем тогда мы создавали свой эксепшн... Я тогда совсем запутался, где нужен наш, где Bad request, где Not Found...

2022-08-03 22:26 UTC, GSBoldyrev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +
Простите простите, не знаю даже, как эти лишние строчки тут появились))

2022-08-03 22:56 UTC, GSBoldyrev commented on pom.xml
> +	</parent>
Почитал про версионирование. То есть, я могу в pom файле поменять версию своего проекта? 
`    <groupId>ru.yandex.practicum</groupId>
    <artifactId>filmorate</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>filmorate</name>
    <description>Приложение для оценки фильмов</description>`
    То есть прям вот здесь поменять версию? И как могу судить из прочитанного, приложение уже тянет на 0.1.0 ))

2022-08-03 22:57 UTC, GSBoldyrev commented on src/main/resources/application.properties
> +
Исправил! Только не понял из статей, файл application.yml будет один для всего? Или их нужно создавать несколько для разных настроек?

2022-08-04 18:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/misc/Validator.java
> +            throw new ValidationException("Логин не может содержать пробелы!");
Ну это мы уже обсудили в slack, я чет не подумал сюда заглядывать за комментами, не привык еще ))

2022-08-04 18:45 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/misc/Validator.java
> +            user.setName(user.getLogin());
С присвоением тогда всё понятно и ты прав, но сделать это надо не в валидаторе

2022-08-04 18:46 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +            throw new ValidationException("Пользователь не найден!");
`BadRequest`, `NotFound` - они все наши будут, родные и любимые ))

2022-08-04 18:57 UTC, FanaticFiz approved these changes

2022-08-04 18:57 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
Ну а дальше вы научитесь правильно их обрабатывать чтобы они (ексепшены) выдавали правильный/соответствующий статус код

2022-08-04 18:57 UTC, FanaticFiz commented on src/test/java/ru/yandex/practicum/filmorate/ValidatorTest.java
>          Film firstFilm =
Хочется подправить твой `code style`

Кажется что эта строка вполне себе помещается в 120

`Film veryOldFilm = new Film("Name", "Description", LocalDate.of(1600, 11, 11), 1);`

Но если ты хочешь осмысленно выделить `new` на новую строку или строка уже не влазит в 120 то

```
Film veryOldFilm = 
        new Film("Name", "Description", LocalDate.of(1600, 11, 11), 1);
```

2022-08-04 18:57 UTC, FanaticFiz commented on pom.xml
> +		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
Криво-косо! )

2022-08-04 18:57 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            throw new NotFoundException("Фильм не найден!");
Давай больше информации... ты же точно знаешь по какому id ты искал, так вот и скажи об этом...

2022-08-05 23:20 UTC, merged

2022-08-07 18:42 UTC, FanaticFiz commented on pom.xml
> +	</parent>
Сейчас это у тебя не пакет, не либа, а прям сервис.
Да именно тут это и делают )
Я был бы смелее и ставил бы гордо 1.0.0
Сори за поздний коммент (

2022-08-07 18:50 UTC, FanaticFiz commented on src/main/resources/application.properties
> +
Я чтот совсем не слежу за комментированием тут, не привык еще...
Файлов с настройками может быть несколько, не советую тебе делать так ближайшие пару лет ))
Ну а потом ты про это забудешь ))