fix: первая итерация 10го спринта
GSBoldyrev/java-filmorate pull request #2
Opened 2022-08-16 00:51 UTC by GSBoldyrev

2022-08-16 19:04 UTC, FanaticFiz requested changes
Финальный коммент на Я.Практикуме

2022-08-16 19:04 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +package ru.yandex.practicum.filmorate.controllers;
Привет, заметил что у тебя два файла пропертей.
Ты же должен был просто поменять расширение ))

Удали `application.properties`.

2022-08-16 19:04 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +
Приведи в порядок именование пакетов. 
На Я.Практикуме рекомендуют именовать в единственном числе. 
`controller`, например. Но точно не в разнобой, в одном месте так, в другом иначе...

2022-08-16 19:04 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +    public ErrorResponse handleBadrequest(final BadRequestException e) {
Опечатка `handleBadRequest`

2022-08-16 19:04 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +    public ErrorResponse handleBadrequest(final BadRequestException e) {
И тут ты наверное тоже хотел вывести сообщение?

`log.error("Bad Request Exception", e.getMessage());`

2022-08-16 19:04 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private final FilmService service;
Надо писать что за `service` -> `filmService`. 
А так слишком обще, знаешь сколько у тебя этих сервисов будет еще )

2022-08-16 19:04 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private final FilmStorage storage;
А этих товарищей тут быть не должно...
`FilmStorage storage`
`UserStorage userStorage`

Весь смысл в том что контроллеры не взаимодействуют с хранилищами напрямую. 

Это всё в сервисе.. из сервиса торчат нужные методы: get/create/update/getAll и т.д.

2022-08-16 19:04 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private final UserStorage storage;
Ну я думаю посыл из предыдущего коммента понятен.
Тут тоже надо изменить.

2022-08-16 19:04 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Integer> friends = new HashSet<>();
Кажется лучше явно прописать что тут лежат только id: `friendIds`

2022-08-16 19:04 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    Film addFilm(Film film);
Не нужно приписывать каждому методу `Film`, методы не висят в воздухе.
Поэтому будет понятно от имени сервиса что происходит.
И потом это даст тебе возможность прокачать свои `storage`... но об этом позже...

2022-08-16 19:04 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        return films.values().stream().sorted(this::compare).limit(count).collect(Collectors.toList());
ЛАПША, должна быть нарезана КРАСИВО !

```
    @Override
    public List<Film> getMostPopularFilms(int count) {
        log.info("Вывод списка наиболее популярных фильмов");
        
        return films.values().stream()
                    .sorted(this::compare)
                    .limit(count)
                    .collect(Collectors.toList());
    }
```

2022-08-16 23:42 UTC, GSBoldyrev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +package ru.yandex.practicum.filmorate.controllers;
Сделано!)

2022-08-16 23:43 UTC, GSBoldyrev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +
И это сделано!)

2022-08-16 23:48 UTC, GSBoldyrev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +    public ErrorResponse handleBadrequest(final BadRequestException e) {
Опечатку убрал, а если в лог ставлю `log.error("Bad Request Exception", e.getMessage());` вместо `log.error("Bad Request Exception", e);` то Идея высвечивает ошибку "More arguments provided (1) than placeholders specified (0)". А я не знаю, что это такое..(

2022-08-16 23:51 UTC, GSBoldyrev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private final FilmService service;
Сделано!)

2022-08-16 23:52 UTC, GSBoldyrev commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Integer> friends = new HashSet<>();
исправил

2022-08-16 23:52 UTC, GSBoldyrev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    Film addFilm(Film film);
Тоже исправил)

2022-08-16 23:52 UTC, GSBoldyrev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        return films.values().stream().sorted(this::compare).limit(count).collect(Collectors.toList());
Нарезал!))

2022-08-17 19:07 UTC, FanaticFiz approved these changes

2022-08-17 19:07 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public Set<User> getMutualFriends(User user1, User user2) {
Ты мог бы передавать сюда id вместо объектов... но по ходу это работы мы это еще успеем переписать, так что оставим как есть.

2022-08-18 00:20 UTC, merged